apiVersion: v1
kind: ConfigMap
metadata:
  name: rentesy-app-config
  namespace: rentesy-app
data:
  NODE_ENV: 'prod'
  DB_HOST: 'postgres-service'
  DB_PORT: '5432'
  DB_USER: 'postgres'
  DB_DATABASE: 'rentesy-app-template'
  S3_ENDPOINT: 'minio-service'
  S3_PORT: '9000'
  S3_ACCESS_KEY: 'minioadmin'
  S3_BUCKET_NAME: 'rentesy-bucket'
  SERVER_PORT: '3000'
  JWT_USER_TOKEN_EXPIRES_IN: '7d'
