apiVersion: v1
kind: Secret
metadata:
  name: rentesy-app-secret
  namespace: rentesy-app
type: Opaque
data:
  # Base64 encoded values
  # DB_PASSWORD: echo -n "your-db-password" | base64
  DB_PASSWORD: MXFhMndzM2Vk # 1qa2ws3ed
  # S3_SECRET_KEY: echo -n "your-s3-secret" | base64
  S3_SECRET_KEY: bWluaW9hZG1pbg== # minioadmin
  # JWT_TOKEN_SECRET: echo -n "your-jwt-secret" | base64
  JWT_TOKEN_SECRET: cHJvZC1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg== # prod-jwt-secret-key-change-in-production
